### ISSUE TITLE
カート機能でまだできていない３点＋α

### ISSUE THREAD

**Issue by 1noseA** [BlueBird1995/BlueBirdCake#32]
・数量のupdate
・destroy_all（カートを空にする）がdestroyアクションが呼び出されてしまう
・情報入力画面に進むボタン（合計金額をorder)
＋
・同じ商品を商品詳細ページからもう一度カートに入れるボタンを押した時、数量が増えずにカートが増えてしまうのは気にしなくてもよいのか

**Comment by yuki-snow1823** [comment]
同名商品があった場合個数を増やすやつ完了しました！

**Comment by 1noseA** [comment]
・destroy_allはroutesのidを消すことで解決（destroyと同じroutes（user/:id/carts）だったのでdestroyが先に呼ばれてしまっていた）
・情報入力へ進むボタンは値を飛ばさなくてよいので完了
