### ISSUE TITLE
[user]Userのstatusをfalseにした場合、ログインできるようにするかわからない(テストの時）

### ISSUE THREAD

**Issue by hikaru9507** [BlueBird1995/BlueBirdCake#35]
#Userステータス
- ステータスがfalseであった時、ログインできないようにした方がいいのかな？

**Comment by yuki-snow1823** [comment]
うーん、再登録しやすいように、再度ログインボタンを押したらtureに切り替えるみたいにもしできれば良いと思う

**Comment by yuki-snow1823** [comment]
テストの時でもいいかもしれませんな
